jobs:
    include:
        -
            stage: test
            env: Type='unit test'
            language: csharp
            dotnet: 2.1.4
            mono: latest
            before_script:
                - nvm install 8
            script:
                - cd test
                - npm i
                - dotnet restore
                - dotnet restore Node/NodeTest.fsproj
                - dotnet fable npm-test
        -
            stage: deploy
            env: Type='node bindings'
            language: csharp
            dotnet: 2.1.4
            mono: latest
            if: branch =~ ^v.+node$
            script:
                - cd Node
                - dotnet pack
                - cd bin/Debug
                - dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_KEY
